Python copy:
    1. Shallow copy
    2. Deep copy

Shallow Copy:
If b is copied from a, then change of a will reflect at change of b

In [3]:
arr1 = [1, 2, 3, 4]
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr1[2] = 9
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1, 2, 3, 4]
[1, 2, 3, 4]
1214333781640
1214333781640
[1, 2, 9, 4]
[1, 2, 9, 4]
1214333781640
1214333781640


In above both arr1 and arr2 pointing to the same memory location. And the change in one array relfect in copied array. So this is a shallow copy.

In [8]:
from numpy import *
arr1 = array([1, 2, 3, 4])
arr2 = arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr1[2] = 9
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4]
[1 2 3 4]
1214338961776
1214338962016
[1 2 9 4]
[1 2 9 4]
1214338961776
1214338962016


In above both arr1 and arr2 pointing to the different memory location. But the change in one array relfect in copied array. So this is a shallow copy.

Deep copy: If b is copied from a then changes of a will not reflect in b

In [11]:
from numpy import *

arr1 = array([1, 2, 3, 4])
arr2 = arr1.copy()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr1[2] = 9
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4]
[1 2 3 4]
1214285190928
1214285192928
[1 2 9 4]
[1 2 3 4]
1214285190928
1214285192928


In above both arr1 and arr2 pointing to the different memory location. And the change in one array is not relfected in copied array. So this is a deep copy.