Different ways to creat array:
1. array()
2. linspace()
3. logspace()
4. arange()
5. zeros()
6. ones()
7. full()
8. random()

In [4]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int)
print(arr.dtype)
print(arr)
arr1 = array([1, 2, 3, 4, 5], float)
print(arr1.dtype)
print(arr1)
arr2 = array([1, 2, 3, 4, 5], str)
print(arr2.dtype)
print(arr2)

int32
[1 2 3 4 5]
float64
[1. 2. 3. 4. 5.]
<U1
['1' '2' '3' '4' '5']


In [8]:
arr3 = linspace(0, 15, 16) #linspace(start, end, number of normal division)
print(arr3)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [9]:
arr4 = logspace(0, 15, 16) #logspace(start, end, number of logarithimic division)
print(arr4)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15]


In [10]:
arr5 = arange(0, 16, 1) #arange(start, end, increament)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
arr6 = zeros(6)
print(arr6)
arr7 = ones(6)
print(arr7)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [5]:
from numpy import *

arr8 = ones((2, 3))
print(arr8)

arr9 = full((2, 3), 5)
print(arr9)

arr10 = random.random((2, 2))
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0.02303135 0.91471126]
 [0.04634374 0.49503523]]
