Boolean Indexing 2D:

In [6]:
import numpy as np

a = np.random.randint(1, 30, (5, 6))
print(a)
bool_a = a > 20
ans = a[bool_a]
print(ans)
b = a
b[bool_a] = 100
print(b)
b[bool_a, 3] = 99
print(b)

[[ 4 11  6 14 16  7]
 [14  6  6 15  1 16]
 [ 7  4 12 17 28  5]
 [29 15 12 18 24 26]
 [27  6 13 10  2 18]]
[28 29 24 26 27]
[[  4  11   6  14  16   7]
 [ 14   6   6  15   1  16]
 [  7   4  12  17 100   5]
 [100  15  12  18 100 100]
 [100   6  13  10   2  18]]


IndexError: too many indices for array