2D Array:

In [7]:
from numpy import *

arr1 = array([
    [1, 2, 3, 7],
    [4, 5, 6, 8]
])

print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

arr2 = arr1.flatten()
print(arr2)

arr3 = arr2.reshape(4, 2)
print(arr3)

arr4 = arr2.reshape(2, 2, 2)
print(arr4)

int32
2
(2, 4)
8
[1 2 3 7 4 5 6 8]
[[1 2]
 [3 7]
 [4 5]
 [6 8]]
[[[1 2]
  [3 7]]

 [[4 5]
  [6 8]]]


Matrix:

In [15]:
from numpy import *

arr5 = array([
    [1, 2, 3],
    [5, 6, 7],
    [4, 8, 9]
])

m1 = matrix(arr5)
print(m1)

m2 = matrix('1, 2, 3; 4, 5, 6; 7, 8 , 9')
print(m2)
print(diagonal(m2))
print(m2.min())
print(m2.max())
m3 = m1 + m2
print(m3)
m4 = m1 * m2
print(m4)

[[1 2 3]
 [5 6 7]
 [4 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
1
9
[[ 2  4  6]
 [ 9 11 13]
 [11 16 18]]
[[ 30  36  42]
 [ 78  96 114]
 [ 99 120 141]]


In [4]:
import numpy as np

arr1 = np.identity(3) # Both gives identity matrix But it only takes one parameter and gives square matrix
print(arr1)

arr2 = np.eye(3) # Both gives identity matrix But it takes 2 argumens to give non square matrix
print(arr2)

arr3 = np.eye(2, 3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]
